; NSIS installer script for REFI ALPHA Windows setup.
; This script is compiled on Linux with makensis.
; Expected source files are generated by scripts/build_windows.py.

!define APP_NAME "REFI ALPHA"
!define APP_VERSION "1.0.0"
!define APP_PUBLISHER "REFI Alpha Team"
!define APP_URL "https://github.com/refi-alpha"
!define APP_EXE "refi-alpha.bat"

Name "${APP_NAME}"
OutFile "..\\dist\\refi-alpha-windows-setup.exe"
InstallDir "$LOCALAPPDATA\Programs\REFI Alpha"
RequestExecutionLevel user
ShowInstDetails show

; Version metadata shown in Windows file properties
VIProductVersion "${APP_VERSION}.0"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "ProductVersion" "${APP_VERSION}"
VIAddVersionKey "CompanyName" "${APP_PUBLISHER}"
VIAddVersionKey "LegalCopyright" "${APP_PUBLISHER}"
VIAddVersionKey "FileDescription" "${APP_NAME} Installer"
VIAddVersionKey "FileVersion" "${APP_VERSION}"

Page directory
Page instfiles

UninstPage uninstConfirm
UninstPage instfiles

Function .onInit
    SetAutoClose false
    MessageBox MB_OK "El instalador de REFI ALPHA se esta ejecutando. Hacer clic en Aceptar para continuar."
FunctionEnd

Section "Install"
    DetailPrint "Instalando REFI ALPHA en $INSTDIR"
    SetOutPath "$INSTDIR"
    File /r "..\\dist\\windows\\staging\\*"
    DetailPrint "Archivos copiados."

    ; Create uninstaller
    WriteUninstaller "$INSTDIR\Uninstall.exe"

    ; Add/Remove Programs registry entries
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\REFIALPHA" "DisplayName" "${APP_NAME}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\REFIALPHA" "UninstallString" "$INSTDIR\Uninstall.exe"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\REFIALPHA" "DisplayVersion" "${APP_VERSION}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\REFIALPHA" "Publisher" "${APP_PUBLISHER}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\REFIALPHA" "URLInfoAbout" "${APP_URL}"

    DetailPrint "Creando accesos directos..."
    CreateShortcut "$DESKTOP\REFI ALPHA.lnk" "$INSTDIR\${APP_EXE}" "" "$INSTDIR\python\python.exe" 0
    CreateDirectory "$SMPROGRAMS\REFI ALPHA"
    CreateShortcut "$SMPROGRAMS\REFI ALPHA\REFI ALPHA.lnk" "$INSTDIR\${APP_EXE}" "" "$INSTDIR\python\python.exe" 0
    CreateShortcut "$SMPROGRAMS\REFI ALPHA\Uninstall.lnk" "$INSTDIR\Uninstall.exe"

    DetailPrint "Instalacion completada."
SectionEnd

Section "Uninstall"
    DetailPrint "Desinstalando REFI ALPHA..."
    Delete "$INSTDIR\Uninstall.exe"
    RMDir /r "$INSTDIR"

    Delete "$DESKTOP\REFI ALPHA.lnk"
    Delete "$SMPROGRAMS\REFI ALPHA\REFI ALPHA.lnk"
    Delete "$SMPROGRAMS\REFI ALPHA\Uninstall.lnk"
    RMDir "$SMPROGRAMS\REFI ALPHA"

    DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\REFIALPHA"
    DetailPrint "Desinstalacion completada."
SectionEnd
